Repository sendbird/chat-ai-widget, pull requests merged in 2024-07, with the labels that each got.

#295 [AC-2950] feat: window object
  src/components/widget/ProviderContainer.tsx
  src/hooks/useAssignGlobalFunction.ts
Labels: 1.7.2

#296 [AC-2970] feat: ignore auto open in mobile view
  src/App.tsx
  src/const.ts
  src/hooks/useWidgetAutoOpen.ts
Labels: 1.7.2

#297 Improve form invalid check logic
  src/components/FormInput.tsx
  src/components/messages/FormMessage.tsx
Labels: 1.7.2

#298 release/v1.7.2
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.7.2

#303 release/v1.7.3
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.7.3

#309 [AC-3297] feat: chatbot playground
  .circleci/config.yml
  packages/self-service/package.json
  packages/self-service/playground.html
  packages/self-service/scripts/build.js
  packages/self-service/scripts/generate-index.js
  packages/self-service/scripts/generateIndex.js
  packages/self-service/scripts/getWidgetVersion.js
  packages/self-service/scripts/widget-version.js
  packages/self-service/vite.config.ts
Labels: 1.7.4

#315 fix: handle error in asSafeURL
  src/__tests__/utils/index.test.ts
  src/utils/index.ts
Labels: 1.7.4

#316 fix: display feedback modal on button click
  src/components/BotMessageFeedback.tsx
Labels: 1.7.4

#320 release: v1.7.4
  .github/workflows/pr-comment-bot.yml
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.7.4
