Repository sendbird/chat-ai-widget, pull requests merged in 2024-08, with the labels that each got.

#322 fix: disconnect web socket should depends on open state
  src/hooks/useWidgetButtonActivityTimeout.ts
Labels: 1.7.5

#327 [AC-3508] fix: update carousel index calculation
  src/components/ui/SnapCarousel/index.tsx
Labels: 1.7.6

#328 [AC-3509] chore: update disconnect ws timeout to 1 min
  src/hooks/useWidgetButtonActivityTimeout.ts
Labels: 1.7.6

#329 [AC-3505] fix: add root element to full screen component for modal
  src/components/widget/WidgetWindowExternal.tsx
  src/components/widget/WidgetWindowFullScreen.tsx
  src/index.ts
Labels: 1.7.6

#331 release: v1.7.7
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  src/components/ui/SnapCarousel/index.tsx
  yarn.lock
Labels: 1.7.7

#334 feat: add enableWidgetExpandButton option
  README.md
  src/components/CustomChannelHeader.tsx
  src/components/widget/WidgetWindow.tsx
  src/const.ts
  src/context/ConstantContext.tsx
Labels: 1.7.8

#335 feat: support tel, mailto, sms scheme
  src/utils/index.ts
Labels: 1.7.8

#337 fix: do not disconnect in full screen mode
  src/components/widget/Chat.tsx
  src/components/widget/WidgetWindowFullScreen.tsx
  src/hooks/useWidgetButtonActivityTimeout.ts
Labels: 1.7.8

#336 ci: update deploy workflows
  .circleci/config.yml
  .github/workflows/self-service-publish.yml
  packages/self-service/scripts/getWidgetVersion.js
  release-guide.md
Labels: 1.7.8

#339 release/v1.7.8
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.7.8

#340 ci: update workflow branches
  .github/workflows/self-service-publish.yml
Labels: 1.7.8

#341 ci: update self-service workflow
  .github/workflows/self-service-publish.yml
Labels: 1.7.8

#347 [AC-3510] feat: add callbacks.onWidgetSettingFailure
  packages/self-service/playground.html
  packages/self-service/playground/chatbot-404.png
  packages/self-service/playground/index.html
  packages/self-service/scripts/generateIndex.js
  src/context/WidgetSettingContext.tsx
  src/libs/api/widgetSetting.ts
  src/types.ts
Labels: 1.7.9

#350 release: v1.7.9
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.7.9

#354 release/v1.7.10
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.7.10
