Repository sendbird/chat-ai-widget, pull requests merged in 2024-05, with the labels that each got.

#196 [AC-2235] feat: added and exported clearCache function
  src/hooks/useWidgetLocalStorage.ts
  src/index.ts
  src/utils/index.ts
Labels: 1.5.4

#199 [AC-2255] Fix incorrect feedback modal position
  src/components/ChatAiWidget.tsx
  src/components/ProviderContainer.tsx
  src/components/WidgetWindow.tsx
  src/const.ts
  src/css/index.css
  src/hooks/useDynamicAttachModal.tsx
Labels: 1.5.4

#197 Added fixateView prop to Constant
  src/App.tsx
  src/components/BotMessageFeedback.tsx
  src/components/ChatAiWidget.tsx
  src/components/CustomChannelHeader.tsx
  src/components/ProviderContainer.tsx
  src/components/WidgetToggleButton.tsx
  src/const.ts
  src/context/ConstantContext.tsx
  src/hooks/useMobileView.ts
  src/utils/index.ts
Labels: 1.5.4

#195 bug-fix: Fix scroll bottom not working with last message with suggested replies
  src/components/CurrentUserMessage.tsx
  src/components/CustomChannelComponent.tsx
  src/components/CustomMessage.tsx
  src/main.tsx
Labels: 1.5.4

#202 release/v1.5.4
  CHANGELOG.md
  package-lock.json
  package.json
  packages/self-service/package.json
Labels: 1.5.4

#204 chore: add manual pkg publish guide to release-guide.md
  release-guide.md
Labels: Ready for review

#205 [AC-2306] feat: support autoOpen to mobile view
  src/components/WidgetToggleButton.tsx
Labels: 1.5.5

#207 bug-fix: Fixed a bug where message input is not being disabled when last message has a suggested replies
  src/components/ProviderContainer.tsx
Labels: 1.5.5

#208 improvement: Increase header button sizes in mobile view
  src/components/CustomChannelHeader.tsx
  src/const.ts
  src/context/ConstantContext.tsx
Labels: 1.5.5

#201 feat: Support realtime update of bot edit props
  src/App.tsx
  src/components/BotMessageWithBodyInput.tsx
  src/components/Chat.tsx
  src/components/CustomChannelComponent.tsx
  src/components/CustomMessage.tsx
  src/components/ParsedBotMessageBody.tsx
  src/components/TokensBody.tsx
  src/const.ts
  src/context/ConstantContext.tsx
  src/hooks/useChannelStyle.ts
  src/utils/index.ts
  src/utils/messages.ts
Labels: 1.5.5

#206 fix: Fixed a bug where multi-line message data content is displayed incorrectly
  src/components/MessageDataContent.tsx
Labels: 1.5.5

#209 bug: Fixed a bug where sender name is overflowing in a bot message.
  src/components/BotMessageWithBodyInput.tsx
Labels: 1.5.5

#210 release/v1.5.5
  CHANGELOG.md
  package-lock.json
  package.json
  packages/self-service/package.json
Labels: 1.5.5

#213 release: v1.5.6
  CHANGELOG.md
  package-lock.json
  package.json
  packages/self-service/package.json
Labels: 1.5.6

#214 chore: Change message sender width to fixed.
  src/components/BotMessageWithBodyInput.tsx
Labels: 1.5.7

#216 feat: Added widgetOpenState and onWidgetOpenStateChange to Constant
  src/App.tsx
  src/components/WidgetToggleButton.tsx
  src/const.ts
  src/context/ConstantContext.tsx
  src/context/WidgetOpenContext.tsx
Labels: 1.5.7

#217 release/v1.5.7
  CHANGELOG.md
  package.json
Labels: 1.5.7

#222 [AC-2366] fix: move target if styled-components is affected by external manipulation
  src/components/ProviderContainer.tsx
  src/hooks/useStyledComponentsTarget.ts
Labels: 1.5.8

#219 fix: Fixed bot studio issues
  src/App.tsx
  src/components/CustomChannelComponent.tsx
  src/components/CustomMessage.tsx
  src/components/InjectedWelcomeMessage.tsx
Labels: 1.5.9

#224 release: v1.5.8
  CHANGELOG.md
  package-lock.json
  package.json
  packages/self-service/package.json
Labels: 1.5.8

#227 chore: Added .yarnrc.yml file to root in order to generate node_modules file when install
  .yarnrc.yml
Labels: 1.5.9

#229 feat: Bring back expand button in desktop view for dashboard only
  src/components/CustomChannelHeader.tsx
  src/components/WidgetWindow.tsx
  src/const.ts
  src/icons/icon-collapse.svg
  src/icons/icon-expand.svg
Labels: 1.5.9

#230 [AC-2387] feat: added enableResetHistoryOnConnect option
  package.json
  src/App.tsx
  src/components/Chat.tsx
  src/components/CustomChannelComponent.tsx
  src/components/CustomMessage.tsx
  src/const.ts
  src/context/ConstantContext.tsx
  src/hooks/useResetHistoryOnConnected.ts
Labels: 1.5.9

#232 chore: Adjust message timestamp margin
  src/components/BotMessageWithBodyInput.tsx
  src/components/CurrentUserMessage.tsx
  src/components/MessageComponent.tsx
  src/components/UserMessageWithBodyInput.tsx
Labels: 1.5.9

#211 [AC-2076] feat: carousel for commerce shop items
  src/components/BotMessageWithBodyInput.tsx
  src/components/CurrentUserMessage.tsx
  src/components/CustomChannelComponent.tsx
  src/components/CustomMessage.tsx
  src/components/MessageComponent.tsx
  src/components/TokensBody.tsx
  src/components/messages/ShopItemsMessage.tsx
  src/components/messages/WelcomeMessages.tsx
  src/components/ui/SnapCarousel/index.tsx
  src/const.ts
  src/context/ConstantContext.tsx
  src/css/index.css
  src/utils/index.ts
  src/utils/messageExtension.ts
  src/utils/messages.ts
Labels: 1.5.9

#231 feat: Added onWidgetExpandStateChange
  src/App.tsx
  src/components/WidgetWindow.tsx
  src/context/ConstantContext.tsx
  src/types.ts
Labels: 1.5.9

#233 fix: Fixed a bug where message bubble width is incorrect in some cases
  src/App.tsx
  src/components/CurrentUserMessage.tsx
  src/components/InjectedWelcomeMessage.tsx
  src/components/MessageComponent.tsx
  src/components/TokensBody.tsx
Labels: 1.5.9

#236 release/v1.5.9
  .circleci/config.yml
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.5.9

#239 release/v1.5.10
  .github/workflows/package-publish.yml
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.5.10

#225 [AC-2365] feat: remove channel style autoOpen
  src/components/ChatAiWidget.tsx
  src/components/WidgetToggleButton.tsx
  src/const.ts
  src/context/WidgetSettingContext.tsx
  src/hooks/useWidgetButtonActivityTimeout.ts
  src/libs/api/widgetSetting.ts
Labels: 1.5.11

#241 fix: inject botStudioEditProps.style to botStyle
  src/const.ts
  src/context/WidgetSettingContext.tsx
Labels: 1.5.11

#242 chore: Display expand button only when callbacks.onWidgetExpandStateChange is given
  src/App.tsx
  src/components/CustomChannelHeader.tsx
  src/components/WidgetWindow.tsx
Labels: 1.5.11

#240 refactor: configureSession as params
  src/App.tsx
  src/components/Chat.tsx
  src/context/ConstantContext.tsx
Labels: 1.5.11

#244 release/v1.5.11
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.5.11

#245 feat: Support horizontal suggested replies.
  src/App.tsx
  src/components/CustomChannelComponent.tsx
  src/components/DynamicRepliesPanel.tsx
  src/components/StaticRepliesPanel.tsx
  src/components/messages/WelcomeMessages.tsx
  src/const.ts
Labels: 1.5.12

#246 chore: Display MessageDataContent for last message only
  src/components/CustomChannelComponent.tsx
Labels: 1.5.12

#250 release: v1.5.12
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.5.12

#252 fix: Fix bug where timestamp is not grouped when welcome message given
  src/components/CustomChannelComponent.tsx
Labels: 1.5.13

#257 chore: Change default value of blockWhileBotResponding to 10000
  src/App.tsx
  src/const.ts
  src/context/ConstantContext.tsx
Labels: 1.6.0

#258 release/v1.6.0
  CHANGELOG.md
  README.md
  package.json
  packages/self-service/package.json
  src/App.tsx
  src/const.ts
  yarn.lock
Labels: 1.6.0
