Repository sendbird/chat-ai-widget, pull requests merged in 2024-04, with the labels that each got.

#138 [AC-1856] Add publish automation workflows
  .github/workflows/gh-deploy.yml
  .github/workflows/package-publish.yml
  packages/self-service/script-publish.md
  release-guide.md
Labels: Ready for review

#152 Fix incorrect feedback icon position
  src/components/BotMessageWithBodyInput.tsx
  src/const.ts
  src/utils/index.ts
Labels: Ready for review

#155 [AC-2074] feat: parse message.data safely
  src/components/ParsedBotMessageBody.tsx
  src/components/SuggestedReplyMessageBody.tsx
  src/utils/messages.ts
Labels: Ready for review

#159 Replace key to contain appId & boId
  src/hooks/useChannelStyle.ts
  src/hooks/useGroupChannel.ts
  src/hooks/useWidgetLocalStorage.ts
Labels: Ready for review

#158 fix: feedback diglog position
  src/components/ChatAiWidget.tsx
  src/components/CustomChannelHeader.tsx
  src/components/ProviderContainer.tsx
  src/components/WidgetToggleButton.tsx
  src/components/WidgetWindow.tsx
  src/const.ts
  src/hooks/useDynamicAttachModal.tsx
Labels: Ready for review

#164 chore: replace ai-chatbot product official website link
  src/components/ChatBottom.tsx
Labels: Ready for review

#166 release: v1.4.2
  .github/workflows/package-publish.yml
  .gitignore
  CHANGELOG.md
  package-lock.json
  package.json
  packages/self-service/package-lock.json
  packages/self-service/package.json
  packages/url-webdemo/package-lock.json
  packages/url-webdemo/package.json
  release-guide.md
Labels: Ready for review

#168 [AC-2091] Put datadog-rum back with dynamic import
  package-lock.json
  package.json
  src/components/ProviderContainer.tsx
  src/hooks/useDatadog.ts
Labels: Ready for review

#170 release: v1.4.3
  .github/workflows/package-publish.yml
  CHANGELOG.md
  package-lock.json
  package.json
  packages/self-service/package-lock.json
  packages/self-service/package.json
  packages/url-webdemo/package-lock.json
  packages/url-webdemo/package.json
Labels: Ready for review

#173 [AC-2152] Increment specification of custom messageInputWrapper style
  src/components/CustomChannelComponent.tsx
  src/components/WidgetWindow.tsx
Labels: Ready for review

#175 Revert "Put datadog-rum back with silm version
  .env.example
  .github/workflows/package-publish.yml
  package-lock.json
  package.json
  src/components/ProviderContainer.tsx
  src/hooks/useDatadog.ts
Labels: Ready for review

#178 chore: update release-guide.md
  .github/workflows/gh-deploy.yml
  .github/workflows/package-publish.yml
  release-guide.md
  screenshot/workflow-guide.png
Labels: Ready for review

#177 feat: add new props for custom apiHost & wsHost
  src/components/ProviderContainer.tsx
  src/const.ts
  src/context/ConstantContext.tsx
  src/hooks/useChannelStyle.ts
  src/utils/index.ts
Labels: Ready for review

#181 realse/v1.4.5
  CHANGELOG.md
  package-lock.json
  package.json
  packages/self-service/package-lock.json
  packages/self-service/package.json
  packages/url-webdemo/package-lock.json
  packages/url-webdemo/package.json
Labels: v1.4.5

#183 v1.4.6
  CHANGELOG.md
  package-lock.json
  package.json
  packages/self-service/package-lock.json
  packages/self-service/package.json
  packages/url-webdemo/package-lock.json
  packages/url-webdemo/package.json
Labels: 1.4.6

#185 [AC-2203] feat: support dynamic service name
  packages/self-service/src/App.tsx
  src/components/CustomChannelComponent.tsx
  src/components/ProviderContainer.tsx
  src/const.ts
  src/context/ConstantContext.tsx
  src/index.ts
  src/utils/index.ts
Labels: v1.4.7

#184 bug-fix: Added missing property url in FunctionCallRequestInfo
  src/components/MessageDataContent.tsx
  src/interfaces.ts
Labels: v1.4.7

#186 release: v1.4.7
  CHANGELOG.md
  package-lock.json
  package.json
  packages/self-service/package-lock.json
  packages/self-service/package.json
  packages/url-webdemo/package-lock.json
  packages/url-webdemo/package.json
Labels: v1.4.7
