Repository sendbird/chat-ai-widget, pull requests merged in 2024-06, with the labels that each got.

#265 release/v1.6.1
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.6.1

#259 feat: Added video message support
  src/App.tsx
  src/components/ChatAiWidget.tsx
  src/components/CustomMessage.tsx
  src/components/FileMessage.tsx
  src/css/index.css
Labels: 1.6.2

#261 [AC-2572] feat: widget_setting by strategy
  .eslintrc.cjs
  README.md
  custom-session-guide.md
  src/components/CustomChannelComponent.tsx
  src/const.ts
  src/context/ConstantContext.tsx
  src/context/WidgetSettingContext.tsx
  src/libs/api/widgetSetting.ts
Labels: 1.6.2

#271 [AC-2602] fix: style issues
  src/components/ChatBottom.tsx
  src/components/CodeSnippet.tsx
  src/components/CustomChannelComponent.tsx
  src/components/CustomChannelHeader.tsx
  src/components/TokensBody.tsx
  src/components/ui/BetaLogo.tsx
  src/components/ui/CodeBlock.tsx
  src/components/ui/PoweredByBanner.tsx
Labels: 1.6.3

#272 release: v1.6.3
  .github/workflows/package-publish.yml
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.6.3

#274 [AC-2721] fix: changed url color to inherit
  src/css/index.css
Labels: 1.6.4

#275 release: v1.6.4
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.6.4

#276 fix: href link should not starts with javascript scheme
  src/__tests__/utils/index.test.ts
  src/components/TokensBody.tsx
  src/utils/index.ts
  vitest.config.ts
Labels: 1.6.5

#270 [AC-2444] feat: custom toggle button
  src/App.tsx
  src/components/widget/Chat.tsx
  src/components/widget/ChatAiWidget.tsx
  src/components/widget/ProviderContainer.tsx
  src/components/widget/WidgetToggleButton.tsx
  src/components/widget/WidgetWindow.tsx
  src/components/widget/WidgetWindowExternal.tsx
  src/const.ts
  src/context/WidgetSettingContext.tsx
  src/icons/bot-outlined.svg
  src/icons/chevron-down.svg
  src/icons/ic-arrow-down.svg
  src/icons/icon-widget-chatbot.svg
  src/index.ts
  src/libs/api/widgetSetting.ts
Labels: 1.6.5

#280 chore: convert null response to undefined
  src/libs/api/widgetSetting.ts
Labels: 1.6.5

#282 release: v1.6.5
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.6.5

#284 [AC-2755] fix: sort valid commerce shop items by matched urls
  src/utils/messageExtension.ts
Labels: 1.6.6

#283 [AC-2708] fix: hide scroll bar
  src/css/index.css
Labels: 1.6.6

#254 [AC-2825] ci: add workflows
  .circleci/config.yml
  package.json
  scripts/build-check-ci.sh
  src/__tests__/utils/index.test.ts
Labels: 1.6.6

#287 release/v1.7.0
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.7.0

#289 [AC-2868] chore: re-introduce deprecated auto-open in bot style
  src/context/WidgetSettingContext.tsx
  src/hooks/useWidgetAutoOpen.ts
  src/hooks/useWidgetButtonActivityTimeout.ts
  src/libs/api/widgetSetting.ts
Labels: 1.7.1

#290 [AC-2850] fix: changed other user message text color
  src/components/UserMessageWithBodyInput.tsx
Labels: 1.7.1

#291 [SDKRLSD-1330] release: v1.7.1
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.7.1
