Repository sendbird/chat-ai-widget, pull requests merged in 2024-09, with the labels that each got.

#359 [AC-3808] feat: support test region in playground
  packages/self-service/playground/index.html
Labels: 1.8.0

#360 release: v1.8.0
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.8.0

#361 fix: added missing prevent ios mobile zoom trick
  src/components/chat/ui/ChatInput.tsx
Labels: 1.8.1

#364 fix: remove wrong style and unused styles
  src/css/index.css
Labels: 1.8.2

#365 release: v1.8.2
  CHANGELOG.md
  package.json
  packages/self-service/package.json
  yarn.lock
Labels: 1.8.2

#363 feat: Added pending & failed message
  src/components/CurrentUserMessage.tsx
  src/components/LoadingScreen.tsx
  src/components/MyMessageStatus.tsx
  src/components/messages/OutgoingFileMessage.tsx
Labels: 1.8.3

#368 [AC-3888] chore: add service name to widget playground
  packages/self-service/playground/index.html
  src/const.ts
Labels: 1.8.3

#369 [AC-3912] feat: added stack direction to message list and set as bottom
  src/components/chat/ui/ChatMessageList.tsx
  src/css/index.css
  src/foundation/components/InfiniteMessageList/index.tsx
  src/theme.ts
Labels: 1.8.3
